key: product-portfolio
d:
  short: Produktentwicklung mit Portfolio-Erarbeitung
  long: >
    Die Bewertung der Studierenden erfolgt auf der Basis eines Produkts, Prototypen oder Artefakts,
    das sie (allein oder im Team) im Rahmen der Veranstaltung entwickeln. Die Bewertung erfolgt durch
    die oder den Lehrenden anhand von gängigen Qualitätskriterien bewertet werden.
    Zusätzlich fließt in die Bewertung ein Portfolio und als Projektbericht ein, in dem
    die Studierenden ihre Tätigkeiten in der Veranstaltung und das Produkt dokumentieren.
    Sie erstellen damit eine systematische Materialsammlung, die den
    Prozess der Wissensaneignung zu den Inhalten des Moduls reflektiert und dokumentiert.
    Dabei reflektieren sie kritisch ihre eigene Leistung und den Lernerfolg.
e:
  short: Product creation in conjunction with portfolio
  long: >
