key: project
d:
  short: Projektarbeit
  long: >
    Die Studierenden führen begleitend zur Veranstaltung ein Projekt durch, und demonstrieren
    damit ihren sicheren Umgang mit den im Modul vermittelten Inhalten. Dieses Projekt
    dient als Grundlage der Bewertung, ggfs. auch in Zusammenhang mit einem Projektbericht,
    der den Entwicklungsprozess und die Ergebnisse beschreibt.
e:
  short: Project work
  long: >

